# This workflow action is not included in the template.
# This action syncs all changes from this repo to the Scaffoldly Template
# as a pull request, so we can internally develop templates and have them
# pushed back to the original template

# TODO: Keep the version in this file in ahead of the template

name: Scaffoldly Template Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SCAFFOLDLY_GITHUB_TOKEN: ${{ secrets.SCAFFOLDLY_TEMPLATE_SYNC_GITHUB_TOKEN }}
  SCAFFOLDLY_TARGET_REPO: scaffoldly/sly-auth-api-template
  VERSION_FILE: package.json
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: prepare
        run: |
          old_version=$(jq -r .version ${{ env.VERSION_FILE }})
          new_version=$(npx semver -i minor $old_version)
          echo "Old version is ${old_version}"
          echo "New version is ${new_version}"
          echo "OLD_VERSION=${old_version}" >> $GITHUB_ENV
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          token: ${{ env.SCAFFOLDLY_GITHUB_TOKEN }}
          repository: ${{ env.SCAFFOLDLY_TARGET_REPO }}
          persist-credentials: true
          fetch-depth: 0
          path: .scaffoldly/template
      - run: |
          rm -fr .git
          cp -R .scaffoldly/template/.git .
          git checkout -b "${{ github.repository }}/${{ env.OLD_VERSION }}"
          git add .
          git restore -s@ -SW -- .scaffoldly
          git restore -s@ -SW -- .github/workflows/slyci-*
      - run: |
          git config --local user.email "github-actions@scaffold.ly"
          git config --local user.name "Scaffoldly GitHub Actions"
          contents="$(jq -r --arg v ${{ env.NEW_VERSION }} '.version = $v' ${{ env.VERSION_FILE }})"
          echo "${contents}" > ${{ env.VERSION_FILE }}
          git add ${{ env.VERSION_FILE }}
          git commit -m "Update to ${{ env.NEW_VERSION }}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.SCAFFOLDLY_GITHUB_TOKEN }}
          repository: ${{ env.SCAFFOLDLY_TARGET_REPO }}
          branch: ${{ github.repository }}/${{ env.OLD_VERSION }}
          force: true
      - run: hub pull-request -b main -h ${{ github.repository }}/${{ env.OLD_VERSION }} -r cnuss -a cnuss
